[package]
name = "sshwarden-agent"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
bitwarden-russh = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ssh-key = { workspace = true, features = ["encryption", "ed25519", "rsa", "getrandom"] }
sysinfo = { workspace = true, features = ["windows"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "sync", "macros", "net", "time"] }
tokio-util = { workspace = true, features = ["codec"] }
tracing = { workspace = true }
sshwarden-config = { path = "../sshwarden-config" }

[target.'cfg(windows)'.dependencies]
pin-project = "1"
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Pipes",
] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[lints]
workspace = true
